
package mx.com.televisa.landamark.client.operations;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.com.televisa.landamark.client.operations.types.ObjectFactory;
import mx.com.televisa.landamark.client.operations.types.OperacionesUsuarioOutputParameters;
import mx.com.televisa.landamark.client.operations.types.PermisosUsuarioInputParameters;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "SecmanDasOperacionesUsuario", targetNamespace = "http://webServices.view.secman.televisa.com.mx/")
@XmlSeeAlso({ ObjectFactory.class })
public interface SecmanDasOperacionesUsuario {


    /**
     *
     * @param arg0
     * @return
     *     returns mx.com.televisa.landamark.client.operations.types.OperacionesUsuarioOutputParameters
     */
    @WebMethod(operationName = "ObtenerOperacionesUsuario")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ObtenerOperacionesUsuario",
                    targetNamespace = "http://webServices.view.secman.televisa.com.mx/",
                    className = "mx.com.televisa.landamark.client.operations.types.ObtenerOperacionesUsuario")
    @ResponseWrapper(localName = "ObtenerOperacionesUsuarioResponse",
                     targetNamespace = "http://webServices.view.secman.televisa.com.mx/",
                     className = "mx.com.televisa.landamark.client.operations.types.ObtenerOperacionesUsuarioResponse")
    public OperacionesUsuarioOutputParameters obtenerOperacionesUsuario(@WebParam(name = "arg0", targetNamespace = "")
                                                                        PermisosUsuarioInputParameters arg0);

}
