
package mx.com.televisa.landamark.client.operations;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "SecmanDasOperacionesUsuarioService",
                  targetNamespace = "http://webServices.view.secman.televisa.com.mx/",
                  wsdlLocation =
                  "http://tvmiddev1.televisa.net:10106/SecmanWebServices/SecmanDasOperacionesUsuarioPort?WSDL#%7Bhttp%3A%2F%2FwebServices.view.secman.televisa.com.mx%2F%7DSecmanDasOperacionesUsuarioService")
public class SecmanDasOperacionesUsuarioService extends Service {

    private final static URL SECMANDASOPERACIONESUSUARIOSERVICE_WSDL_LOCATION;
    private final static WebServiceException SECMANDASOPERACIONESUSUARIOSERVICE_EXCEPTION;
    private final static QName SECMANDASOPERACIONESUSUARIOSERVICE_QNAME =
        new QName("http://webServices.view.secman.televisa.com.mx/", "SecmanDasOperacionesUsuarioService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://tvmiddev1.televisa.net:10106/SecmanWebServices/SecmanDasOperacionesUsuarioPort?WSDL#%7Bhttp%3A%2F%2FwebServices.view.secman.televisa.com.mx%2F%7DSecmanDasOperacionesUsuarioService");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SECMANDASOPERACIONESUSUARIOSERVICE_WSDL_LOCATION = url;
        SECMANDASOPERACIONESUSUARIOSERVICE_EXCEPTION = e;
    }

    public SecmanDasOperacionesUsuarioService() {
        super(__getWsdlLocation(), SECMANDASOPERACIONESUSUARIOSERVICE_QNAME);
    }

    public SecmanDasOperacionesUsuarioService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SECMANDASOPERACIONESUSUARIOSERVICE_QNAME, features);
    }

    public SecmanDasOperacionesUsuarioService(URL wsdlLocation) {
        super(wsdlLocation, SECMANDASOPERACIONESUSUARIOSERVICE_QNAME);
    }

    public SecmanDasOperacionesUsuarioService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SECMANDASOPERACIONESUSUARIOSERVICE_QNAME, features);
    }

    public SecmanDasOperacionesUsuarioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecmanDasOperacionesUsuarioService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SecmanDasOperacionesUsuario
     */
    @WebEndpoint(name = "SecmanDasOperacionesUsuarioPort")
    public SecmanDasOperacionesUsuario getSecmanDasOperacionesUsuarioPort() {
        return super.getPort(new QName("http://webServices.view.secman.televisa.com.mx/",
                                       "SecmanDasOperacionesUsuarioPort"), SecmanDasOperacionesUsuario.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SecmanDasOperacionesUsuario
     */
    @WebEndpoint(name = "SecmanDasOperacionesUsuarioPort")
    public SecmanDasOperacionesUsuario getSecmanDasOperacionesUsuarioPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webServices.view.secman.televisa.com.mx/",
                                       "SecmanDasOperacionesUsuarioPort"), SecmanDasOperacionesUsuario.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SECMANDASOPERACIONESUSUARIOSERVICE_EXCEPTION != null) {
            throw SECMANDASOPERACIONESUSUARIOSERVICE_EXCEPTION;
        }
        return SECMANDASOPERACIONESUSUARIOSERVICE_WSDL_LOCATION;
    }

}
