package mx.com.televisa.landamark.client.auth;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.1.3.0.0.1008
public class SecmanBsAutenticarSoap12HttpPortClient {
    public static void main(String[] args) {
        SecmanBsAutenticar_Service secmanBsAutenticar_Service = new SecmanBsAutenticar_Service();
        SecmanBsAutenticar secmanBsAutenticar = secmanBsAutenticar_Service.getSecmanBsAutenticarSoap12HttpPort();
        // Add your code to call the desired methods.


    }
}
