
package mx.com.televisa.landamark.client.auth;

import java.util.concurrent.Future;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

import mx.com.televisa.landamark.client.auth.types.AutenticarUsuarioResponse;
import mx.com.televisa.landamark.client.auth.types.ObjectFactory;
import mx.com.televisa.landamark.client.auth.types.ProcessResponse;
import mx.com.televisa.landamark.client.auth.types.UserLogin;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "SecmanBsAutenticar", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({ ObjectFactory.class })
public interface SecmanBsAutenticar {
   
    @WebMethod(operationName = "autenticarUsuario")
    @RequestWrapper(localName = "autenticarUsuario", targetNamespace = "http://tempuri.org/",
                    className = "mx.com.televisa.landamark.client.auth.types.AutenticarUsuario")
    @ResponseWrapper(localName = "autenticarUsuarioResponse", targetNamespace = "http://tempuri.org/",
                     className = "mx.com.televisa.landamark.client.auth.types.AutenticarUsuarioResponse")
    public Response<AutenticarUsuarioResponse> autenticarUsuarioAsync(@WebParam(name = "UserLogin",
                                                                                targetNamespace = "")
                                                                      UserLogin userLogin);

    /**
     *
     * @param asyncHandler
     * @param userLogin
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "autenticarUsuario")
    @RequestWrapper(localName = "autenticarUsuario", targetNamespace = "http://tempuri.org/",
                    className = "mx.com.televisa.landamark.client.auth.types.AutenticarUsuario")
    @ResponseWrapper(localName = "autenticarUsuarioResponse", targetNamespace = "http://tempuri.org/",
                     className = "mx.com.televisa.landamark.client.auth.types.AutenticarUsuarioResponse")
    public Future<?> autenticarUsuarioAsync(@WebParam(name = "UserLogin", targetNamespace = "") UserLogin userLogin,
                                            @WebParam(name = "asyncHandler", targetNamespace = "")
                                            AsyncHandler<AutenticarUsuarioResponse> asyncHandler);

    /**
     *
     * @param userLogin
     * @return
     *     returns mx.com.televisa.landamark.client.auth.types.ProcessResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "autenticarUsuario", targetNamespace = "http://tempuri.org/",
                    className = "mx.com.televisa.landamark.client.auth.types.AutenticarUsuario")
    @ResponseWrapper(localName = "autenticarUsuarioResponse", targetNamespace = "http://tempuri.org/",
                     className = "mx.com.televisa.landamark.client.auth.types.AutenticarUsuarioResponse")
    public ProcessResponse autenticarUsuario(@WebParam(name = "UserLogin", targetNamespace = "") UserLogin userLogin);

}
