
package mx.com.televisa.landamark.client.auth;

import javax.xml.ws.Response;

import mx.com.televisa.landamark.client.auth.types.AutenticarUsuarioResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
public interface SecmanBsAutenticarAsyncHandler {


    /**
     *
     * @param response
     */
    public void onAutenticarUsuarioResponse(Response<AutenticarUsuarioResponse> response);

}
