package mx.com.televisa.landamark.model;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 08 18:02:59 CST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for EvetvIntConfigParamTabView1.
     * @return EvetvIntConfigParamTabView1
     */
    public ViewObjectImpl getEvetvIntConfigParamTabView1() {
        return (ViewObjectImpl) findViewObject("EvetvIntConfigParamTabView1");
    }
}

