package mx.com.televisa.landamark.model;

import java.sql.Timestamp;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 29 20:06:52 CST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LmkIntCronConfigTabViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_LMKINTCRONCONFIGTAB = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        IdConfiguration,
        IdService,
        IndPeriodicity,
        IndBeginSchedule,
        IndBeginMinute,
        IndBeginSecond,
        IndEndSchedule,
        IndEndMinute,
        IndEndSecond,
        IndTypeSchedule,
        IndValTypeSchedule,
        IndMonday,
        IndTuesday,
        IndWednesday,
        IndThursday,
        IndFriday,
        IndSaturday,
        IndSunday,
        IndDayMonth,
        IndWeekMonth,
        IndCronExpression,
        IndEstatus,
        AttributeCategory,
        Attribute1,
        Attribute2,
        Attribute3,
        Attribute4,
        Attribute5,
        Attribute6,
        Attribute7,
        Attribute8,
        Attribute9,
        Attribute10,
        Attribute11,
        Attribute12,
        Attribute13,
        Attribute14,
        Attribute15,
        FecCreationDate,
        NumCreatedBy,
        FecLastUpdateDate,
        NumLastUpdatedBy,
        NumLastUpdateLogin;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int IDCONFIGURATION = AttributesEnum.IdConfiguration.index();
    public static final int IDSERVICE = AttributesEnum.IdService.index();
    public static final int INDPERIODICITY = AttributesEnum.IndPeriodicity.index();
    public static final int INDBEGINSCHEDULE = AttributesEnum.IndBeginSchedule.index();
    public static final int INDBEGINMINUTE = AttributesEnum.IndBeginMinute.index();
    public static final int INDBEGINSECOND = AttributesEnum.IndBeginSecond.index();
    public static final int INDENDSCHEDULE = AttributesEnum.IndEndSchedule.index();
    public static final int INDENDMINUTE = AttributesEnum.IndEndMinute.index();
    public static final int INDENDSECOND = AttributesEnum.IndEndSecond.index();
    public static final int INDTYPESCHEDULE = AttributesEnum.IndTypeSchedule.index();
    public static final int INDVALTYPESCHEDULE = AttributesEnum.IndValTypeSchedule.index();
    public static final int INDMONDAY = AttributesEnum.IndMonday.index();
    public static final int INDTUESDAY = AttributesEnum.IndTuesday.index();
    public static final int INDWEDNESDAY = AttributesEnum.IndWednesday.index();
    public static final int INDTHURSDAY = AttributesEnum.IndThursday.index();
    public static final int INDFRIDAY = AttributesEnum.IndFriday.index();
    public static final int INDSATURDAY = AttributesEnum.IndSaturday.index();
    public static final int INDSUNDAY = AttributesEnum.IndSunday.index();
    public static final int INDDAYMONTH = AttributesEnum.IndDayMonth.index();
    public static final int INDWEEKMONTH = AttributesEnum.IndWeekMonth.index();
    public static final int INDCRONEXPRESSION = AttributesEnum.IndCronExpression.index();
    public static final int INDESTATUS = AttributesEnum.IndEstatus.index();
    public static final int ATTRIBUTECATEGORY = AttributesEnum.AttributeCategory.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int FECCREATIONDATE = AttributesEnum.FecCreationDate.index();
    public static final int NUMCREATEDBY = AttributesEnum.NumCreatedBy.index();
    public static final int FECLASTUPDATEDATE = AttributesEnum.FecLastUpdateDate.index();
    public static final int NUMLASTUPDATEDBY = AttributesEnum.NumLastUpdatedBy.index();
    public static final int NUMLASTUPDATELOGIN = AttributesEnum.NumLastUpdateLogin.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LmkIntCronConfigTabViewRowImpl() {
    }

    /**
     * Gets LmkIntCronConfigTab entity object.
     * @return the LmkIntCronConfigTab
     */
    public EntityImpl getLmkIntCronConfigTab() {
        return (EntityImpl) getEntity(ENTITY_LMKINTCRONCONFIGTAB);
    }

    /**
     * Gets the attribute value for ID_CONFIGURATION using the alias name IdConfiguration.
     * @return the ID_CONFIGURATION
     */
    public Integer getIdConfiguration() {
        return (Integer) getAttributeInternal(IDCONFIGURATION);
    }

    /**
     * Sets <code>value</code> as attribute value for ID_CONFIGURATION using the alias name IdConfiguration.
     * @param value value to set the ID_CONFIGURATION
     */
    public void setIdConfiguration(Integer value) {
        setAttributeInternal(IDCONFIGURATION, value);
    }

    /**
     * Gets the attribute value for ID_SERVICE using the alias name IdService.
     * @return the ID_SERVICE
     */
    public Integer getIdService() {
        return (Integer) getAttributeInternal(IDSERVICE);
    }

    /**
     * Sets <code>value</code> as attribute value for ID_SERVICE using the alias name IdService.
     * @param value value to set the ID_SERVICE
     */
    public void setIdService(Integer value) {
        setAttributeInternal(IDSERVICE, value);
    }

    /**
     * Gets the attribute value for IND_PERIODICITY using the alias name IndPeriodicity.
     * @return the IND_PERIODICITY
     */
    public String getIndPeriodicity() {
        return (String) getAttributeInternal(INDPERIODICITY);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_PERIODICITY using the alias name IndPeriodicity.
     * @param value value to set the IND_PERIODICITY
     */
    public void setIndPeriodicity(String value) {
        setAttributeInternal(INDPERIODICITY, value);
    }

    /**
     * Gets the attribute value for IND_BEGIN_SCHEDULE using the alias name IndBeginSchedule.
     * @return the IND_BEGIN_SCHEDULE
     */
    public String getIndBeginSchedule() {
        return (String) getAttributeInternal(INDBEGINSCHEDULE);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_BEGIN_SCHEDULE using the alias name IndBeginSchedule.
     * @param value value to set the IND_BEGIN_SCHEDULE
     */
    public void setIndBeginSchedule(String value) {
        setAttributeInternal(INDBEGINSCHEDULE, value);
    }

    /**
     * Gets the attribute value for IND_BEGIN_MINUTE using the alias name IndBeginMinute.
     * @return the IND_BEGIN_MINUTE
     */
    public String getIndBeginMinute() {
        return (String) getAttributeInternal(INDBEGINMINUTE);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_BEGIN_MINUTE using the alias name IndBeginMinute.
     * @param value value to set the IND_BEGIN_MINUTE
     */
    public void setIndBeginMinute(String value) {
        setAttributeInternal(INDBEGINMINUTE, value);
    }

    /**
     * Gets the attribute value for IND_BEGIN_SECOND using the alias name IndBeginSecond.
     * @return the IND_BEGIN_SECOND
     */
    public String getIndBeginSecond() {
        return (String) getAttributeInternal(INDBEGINSECOND);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_BEGIN_SECOND using the alias name IndBeginSecond.
     * @param value value to set the IND_BEGIN_SECOND
     */
    public void setIndBeginSecond(String value) {
        setAttributeInternal(INDBEGINSECOND, value);
    }

    /**
     * Gets the attribute value for IND_END_SCHEDULE using the alias name IndEndSchedule.
     * @return the IND_END_SCHEDULE
     */
    public String getIndEndSchedule() {
        return (String) getAttributeInternal(INDENDSCHEDULE);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_END_SCHEDULE using the alias name IndEndSchedule.
     * @param value value to set the IND_END_SCHEDULE
     */
    public void setIndEndSchedule(String value) {
        setAttributeInternal(INDENDSCHEDULE, value);
    }

    /**
     * Gets the attribute value for IND_END_MINUTE using the alias name IndEndMinute.
     * @return the IND_END_MINUTE
     */
    public String getIndEndMinute() {
        return (String) getAttributeInternal(INDENDMINUTE);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_END_MINUTE using the alias name IndEndMinute.
     * @param value value to set the IND_END_MINUTE
     */
    public void setIndEndMinute(String value) {
        setAttributeInternal(INDENDMINUTE, value);
    }

    /**
     * Gets the attribute value for IND_END_SECOND using the alias name IndEndSecond.
     * @return the IND_END_SECOND
     */
    public String getIndEndSecond() {
        return (String) getAttributeInternal(INDENDSECOND);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_END_SECOND using the alias name IndEndSecond.
     * @param value value to set the IND_END_SECOND
     */
    public void setIndEndSecond(String value) {
        setAttributeInternal(INDENDSECOND, value);
    }

    /**
     * Gets the attribute value for IND_TYPE_SCHEDULE using the alias name IndTypeSchedule.
     * @return the IND_TYPE_SCHEDULE
     */
    public String getIndTypeSchedule() {
        return (String) getAttributeInternal(INDTYPESCHEDULE);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_TYPE_SCHEDULE using the alias name IndTypeSchedule.
     * @param value value to set the IND_TYPE_SCHEDULE
     */
    public void setIndTypeSchedule(String value) {
        setAttributeInternal(INDTYPESCHEDULE, value);
    }

    /**
     * Gets the attribute value for IND_VAL_TYPE_SCHEDULE using the alias name IndValTypeSchedule.
     * @return the IND_VAL_TYPE_SCHEDULE
     */
    public String getIndValTypeSchedule() {
        return (String) getAttributeInternal(INDVALTYPESCHEDULE);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_VAL_TYPE_SCHEDULE using the alias name IndValTypeSchedule.
     * @param value value to set the IND_VAL_TYPE_SCHEDULE
     */
    public void setIndValTypeSchedule(String value) {
        setAttributeInternal(INDVALTYPESCHEDULE, value);
    }

    /**
     * Gets the attribute value for IND_MONDAY using the alias name IndMonday.
     * @return the IND_MONDAY
     */
    public Integer getIndMonday() {
        return (Integer) getAttributeInternal(INDMONDAY);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_MONDAY using the alias name IndMonday.
     * @param value value to set the IND_MONDAY
     */
    public void setIndMonday(Integer value) {
        setAttributeInternal(INDMONDAY, value);
    }

    /**
     * Gets the attribute value for IND_TUESDAY using the alias name IndTuesday.
     * @return the IND_TUESDAY
     */
    public Integer getIndTuesday() {
        return (Integer) getAttributeInternal(INDTUESDAY);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_TUESDAY using the alias name IndTuesday.
     * @param value value to set the IND_TUESDAY
     */
    public void setIndTuesday(Integer value) {
        setAttributeInternal(INDTUESDAY, value);
    }

    /**
     * Gets the attribute value for IND_WEDNESDAY using the alias name IndWednesday.
     * @return the IND_WEDNESDAY
     */
    public Integer getIndWednesday() {
        return (Integer) getAttributeInternal(INDWEDNESDAY);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_WEDNESDAY using the alias name IndWednesday.
     * @param value value to set the IND_WEDNESDAY
     */
    public void setIndWednesday(Integer value) {
        setAttributeInternal(INDWEDNESDAY, value);
    }

    /**
     * Gets the attribute value for IND_THURSDAY using the alias name IndThursday.
     * @return the IND_THURSDAY
     */
    public Integer getIndThursday() {
        return (Integer) getAttributeInternal(INDTHURSDAY);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_THURSDAY using the alias name IndThursday.
     * @param value value to set the IND_THURSDAY
     */
    public void setIndThursday(Integer value) {
        setAttributeInternal(INDTHURSDAY, value);
    }

    /**
     * Gets the attribute value for IND_FRIDAY using the alias name IndFriday.
     * @return the IND_FRIDAY
     */
    public Integer getIndFriday() {
        return (Integer) getAttributeInternal(INDFRIDAY);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_FRIDAY using the alias name IndFriday.
     * @param value value to set the IND_FRIDAY
     */
    public void setIndFriday(Integer value) {
        setAttributeInternal(INDFRIDAY, value);
    }

    /**
     * Gets the attribute value for IND_SATURDAY using the alias name IndSaturday.
     * @return the IND_SATURDAY
     */
    public Integer getIndSaturday() {
        return (Integer) getAttributeInternal(INDSATURDAY);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_SATURDAY using the alias name IndSaturday.
     * @param value value to set the IND_SATURDAY
     */
    public void setIndSaturday(Integer value) {
        setAttributeInternal(INDSATURDAY, value);
    }

    /**
     * Gets the attribute value for IND_SUNDAY using the alias name IndSunday.
     * @return the IND_SUNDAY
     */
    public Integer getIndSunday() {
        return (Integer) getAttributeInternal(INDSUNDAY);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_SUNDAY using the alias name IndSunday.
     * @param value value to set the IND_SUNDAY
     */
    public void setIndSunday(Integer value) {
        setAttributeInternal(INDSUNDAY, value);
    }

    /**
     * Gets the attribute value for IND_DAY_MONTH using the alias name IndDayMonth.
     * @return the IND_DAY_MONTH
     */
    public Integer getIndDayMonth() {
        return (Integer) getAttributeInternal(INDDAYMONTH);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_DAY_MONTH using the alias name IndDayMonth.
     * @param value value to set the IND_DAY_MONTH
     */
    public void setIndDayMonth(Integer value) {
        setAttributeInternal(INDDAYMONTH, value);
    }

    /**
     * Gets the attribute value for IND_WEEK_MONTH using the alias name IndWeekMonth.
     * @return the IND_WEEK_MONTH
     */
    public Integer getIndWeekMonth() {
        return (Integer) getAttributeInternal(INDWEEKMONTH);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_WEEK_MONTH using the alias name IndWeekMonth.
     * @param value value to set the IND_WEEK_MONTH
     */
    public void setIndWeekMonth(Integer value) {
        setAttributeInternal(INDWEEKMONTH, value);
    }

    /**
     * Gets the attribute value for IND_CRON_EXPRESSION using the alias name IndCronExpression.
     * @return the IND_CRON_EXPRESSION
     */
    public String getIndCronExpression() {
        return (String) getAttributeInternal(INDCRONEXPRESSION);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_CRON_EXPRESSION using the alias name IndCronExpression.
     * @param value value to set the IND_CRON_EXPRESSION
     */
    public void setIndCronExpression(String value) {
        setAttributeInternal(INDCRONEXPRESSION, value);
    }

    /**
     * Gets the attribute value for IND_ESTATUS using the alias name IndEstatus.
     * @return the IND_ESTATUS
     */
    public String getIndEstatus() {
        return (String) getAttributeInternal(INDESTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_ESTATUS using the alias name IndEstatus.
     * @param value value to set the IND_ESTATUS
     */
    public void setIndEstatus(String value) {
        setAttributeInternal(INDESTATUS, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @return the ATTRIBUTE_CATEGORY
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @param value value to set the ATTRIBUTE_CATEGORY
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for FEC_CREATION_DATE using the alias name FecCreationDate.
     * @return the FEC_CREATION_DATE
     */
    public Timestamp getFecCreationDate() {
        return (Timestamp) getAttributeInternal(FECCREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for FEC_CREATION_DATE using the alias name FecCreationDate.
     * @param value value to set the FEC_CREATION_DATE
     */
    public void setFecCreationDate(Timestamp value) {
        setAttributeInternal(FECCREATIONDATE, value);
    }

    /**
     * Gets the attribute value for NUM_CREATED_BY using the alias name NumCreatedBy.
     * @return the NUM_CREATED_BY
     */
    public Integer getNumCreatedBy() {
        return (Integer) getAttributeInternal(NUMCREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for NUM_CREATED_BY using the alias name NumCreatedBy.
     * @param value value to set the NUM_CREATED_BY
     */
    public void setNumCreatedBy(Integer value) {
        setAttributeInternal(NUMCREATEDBY, value);
    }

    /**
     * Gets the attribute value for FEC_LAST_UPDATE_DATE using the alias name FecLastUpdateDate.
     * @return the FEC_LAST_UPDATE_DATE
     */
    public Timestamp getFecLastUpdateDate() {
        return (Timestamp) getAttributeInternal(FECLASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for FEC_LAST_UPDATE_DATE using the alias name FecLastUpdateDate.
     * @param value value to set the FEC_LAST_UPDATE_DATE
     */
    public void setFecLastUpdateDate(Timestamp value) {
        setAttributeInternal(FECLASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for NUM_LAST_UPDATED_BY using the alias name NumLastUpdatedBy.
     * @return the NUM_LAST_UPDATED_BY
     */
    public Integer getNumLastUpdatedBy() {
        return (Integer) getAttributeInternal(NUMLASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for NUM_LAST_UPDATED_BY using the alias name NumLastUpdatedBy.
     * @param value value to set the NUM_LAST_UPDATED_BY
     */
    public void setNumLastUpdatedBy(Integer value) {
        setAttributeInternal(NUMLASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for NUM_LAST_UPDATE_LOGIN using the alias name NumLastUpdateLogin.
     * @return the NUM_LAST_UPDATE_LOGIN
     */
    public Integer getNumLastUpdateLogin() {
        return (Integer) getAttributeInternal(NUMLASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for NUM_LAST_UPDATE_LOGIN using the alias name NumLastUpdateLogin.
     * @param value value to set the NUM_LAST_UPDATE_LOGIN
     */
    public void setNumLastUpdateLogin(Integer value) {
        setAttributeInternal(NUMLASTUPDATELOGIN, value);
    }
}

