
package mx.com.televisa.landamark.client.userpermission;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "SecmanDasUsuarioPermisosService",
                  targetNamespace = "http://webServices.view.secman.televisa.com.mx/",
                  wsdlLocation =
                  "http://tvmiddev1.televisa.net:10106/SecmanWebServices/SecmanDasUsuarioPermisosPort?WSDL#%7Bhttp%3A%2F%2FwebServices.view.secman.televisa.com.mx%2F%7DSecmanDasUsuarioPermisosService")
public class SecmanDasUsuarioPermisosService extends Service {

    private final static URL SECMANDASUSUARIOPERMISOSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SECMANDASUSUARIOPERMISOSSERVICE_EXCEPTION;
    private final static QName SECMANDASUSUARIOPERMISOSSERVICE_QNAME =
        new QName("http://webServices.view.secman.televisa.com.mx/", "SecmanDasUsuarioPermisosService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://tvmiddev1.televisa.net:10106/SecmanWebServices/SecmanDasUsuarioPermisosPort?WSDL#%7Bhttp%3A%2F%2FwebServices.view.secman.televisa.com.mx%2F%7DSecmanDasUsuarioPermisosService");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SECMANDASUSUARIOPERMISOSSERVICE_WSDL_LOCATION = url;
        SECMANDASUSUARIOPERMISOSSERVICE_EXCEPTION = e;
    }

    public SecmanDasUsuarioPermisosService() {
        super(__getWsdlLocation(), SECMANDASUSUARIOPERMISOSSERVICE_QNAME);
    }

    public SecmanDasUsuarioPermisosService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SECMANDASUSUARIOPERMISOSSERVICE_QNAME, features);
    }

    public SecmanDasUsuarioPermisosService(URL wsdlLocation) {
        super(wsdlLocation, SECMANDASUSUARIOPERMISOSSERVICE_QNAME);
    }

    public SecmanDasUsuarioPermisosService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SECMANDASUSUARIOPERMISOSSERVICE_QNAME, features);
    }

    public SecmanDasUsuarioPermisosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecmanDasUsuarioPermisosService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SecmanDasUsuarioPermisos
     */
    @WebEndpoint(name = "SecmanDasUsuarioPermisosPort")
    public SecmanDasUsuarioPermisos getSecmanDasUsuarioPermisosPort() {
        return super.getPort(new QName("http://webServices.view.secman.televisa.com.mx/",
                                       "SecmanDasUsuarioPermisosPort"), SecmanDasUsuarioPermisos.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SecmanDasUsuarioPermisos
     */
    @WebEndpoint(name = "SecmanDasUsuarioPermisosPort")
    public SecmanDasUsuarioPermisos getSecmanDasUsuarioPermisosPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webServices.view.secman.televisa.com.mx/",
                                       "SecmanDasUsuarioPermisosPort"), SecmanDasUsuarioPermisos.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SECMANDASUSUARIOPERMISOSSERVICE_EXCEPTION != null) {
            throw SECMANDASUSUARIOPERMISOSSERVICE_EXCEPTION;
        }
        return SECMANDASUSUARIOPERMISOSSERVICE_WSDL_LOCATION;
    }

}
