
package mx.com.televisa.landamark.client.userpermission;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.com.televisa.landamark.client.userpermission.types.ObjectFactory;
import mx.com.televisa.landamark.client.userpermission.types.PermisoOutputCollection;
import mx.com.televisa.landamark.client.userpermission.types.PermisosUsuarioInputParameters;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "SecmanDasUsuarioPermisos", targetNamespace = "http://webServices.view.secman.televisa.com.mx/")
@XmlSeeAlso({ ObjectFactory.class })
public interface SecmanDasUsuarioPermisos {


    /**
     *
     * @param arg0
     * @return
     *     returns mx.com.televisa.landamark.client.userpermission.types.PermisoOutputCollection
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerRolTareaPermisos",
                    targetNamespace = "http://webServices.view.secman.televisa.com.mx/",
                    className = "mx.com.televisa.landamark.client.userpermission.types.ObtenerRolTareaPermisos")
    @ResponseWrapper(localName = "obtenerRolTareaPermisosResponse",
                     targetNamespace = "http://webServices.view.secman.televisa.com.mx/",
                     className =
                     "mx.com.televisa.landamark.client.userpermission.types.ObtenerRolTareaPermisosResponse")
    public PermisoOutputCollection obtenerRolTareaPermisos(@WebParam(name = "arg0", targetNamespace = "")
                                                           PermisosUsuarioInputParameters arg0);

}
